version: 2
updates:
  # GitHub Actions - updates uses: statements in workflows
  - package-ecosystem: "github-actions"
    directory: "/"                  # Where your .github/workflows/ folder is
    schedule:
      interval: "monthly"
  
  # NPM
  - package-ecosystem: "npm"
    directory: "/system/exceptions"  # adjust if needed
    schedule:
      interval: "monthly"
